### ISSUE TITLE
Ability to save the state of the program after n function evalutions

### ISSUE THREAD

**Issue by ilija139** [dme65/pySOT#10]
It would be very useful if it's possible to save the state of the program after every function evaluation. One function evaluation can take several hours, so server crash after 200 or something function evaluation is very painful :sweat_smile:

**Comment by dme65** [comment]
I agree that this is something pySOT really should support and it is something that we have wanted to add for a long time. For the purpose of pySOT it really feels like a necessity. I will keep you updated on my progress!

**Comment by dbindel** [comment]
Added this as an issue on the POAP repo and assigned it to myself.  This will require some changes to pySOT as well, so I will ping you when the update is ready.

**Comment by davebs** [comment]
Not sure if I should create a separate issue for this, but I was wondering how to *reload* the state of the model from saved X, fX pairs? 

Specifically, I'm logging each X, fX result and running for 20 iterations. Now, I'd like to run for another 20 iterations, using the logged X, fX pairs to bootstrap off of so I don't have to restart everything.

```python
controller=SerialController(data.objfunction)
exp_design = LatinHypercube(dim=data.dim, npts=2*(data.dim+1))
response_surface = RBFInterpolant(kernel=CubicKernel, maxp=200)
sampler = CandidateDYCORS(data=data, numcand=100*data.dim)
strategy = \
    SyncStrategyNoConstraints(
        worker_id=0, data=data,
        maxeval=maxeval, nsamples=nsamples,
        exp_design=exp_design,
        response_surface=response_surface,
        sampling_method=sampler)
controller.strategy = strategy

# bootstrap from my log data, supply X, fX pairs?
old_Xs, old_Ys = get_saved_data('logs/') # these come back as list of numpy float arrays 
                                         # and list of floats representing fX evaluation results
for X,Y in zip(old_Xs, old_Ys):
    response_surface.add_point(X, Y)

result = controller.run()

```

But that doesn't work (as evidenced by the fact that the controller picks the same parameters it used at the beginning of training last time, so it's restarting rather than picking up where it left off). 

I also tried adding points to the response surface before initializing the strategy, but that doesn't work either.

Maybe I'm missing something about the math, but it seems like this should be possible? Any ideas?

**Comment by dme65** [comment]
This currently isn't possible, but it's a functionality that we definitely want to add. @dbindel, this is currently assigned to you. Do you want me to take a stab at adding this to POAP?

**Comment by ilija139** [comment]
@davebs As a workaround, you can add a dummy objective function that will return the pre-computed objective values for the given parameters from a cache, i.e. modify the objective function to cache the results and save the cache to disk.

**Comment by dme65** [comment]
I am assigning this to myself and I hope to have a solution within the next few weeks. Thank you for being patient.

**Comment by davebs** [comment]
Hey, no worries, thanks for looking into it! I have used a hack in the meantime that probably makes things not as accurate but still better than random search... This would be a cool feature though, so glad to hear it's going in.

**Comment by the-alleged-car** [comment]
@dme65, can the enhancement you added to solve https://github.com/dme65/pySOT/issues/16 also be used to solve @davebs problem above in https://github.com/dme65/pySOT/issues/10#issuecomment-310451806?

**Comment by dme65** [comment]
No, as it doesn't keep the values of some of the internal strategy parameters. I'm currently working on this, however, and it will be added to the next version of pySOT. I'm a few weeks away from being ready to release it. It will be quite different from the current version and there will be more features and a much cleaner framework design.

**Comment by davidsblom** [comment]
Are there any updates on this issue? I'd like to use restarting of the optimization procedure as well.

**Comment by dme65** [comment]
The checkpointing feature has been added on my own branch. Version 0.2.0 is on its way! I just need to make a few more changes to the code and update the documentation!

**Comment by dme65** [comment]
A CheckpointController has been added in v0.2.0.
