### ISSUE TITLE
mpiexample_simple.py fails after the increase of number of workers

### ISSUE THREAD

**Issue by vvmikheev** [dme65/pySOT#37]
I am trying to run the script using this command:

mpiexec -n 20 python mpi_example.py

Unfortunately, it fails with AssertionError. And it works just fine with 10 workers (example below.)
Could you please explain what has happened?

![image](https://user-images.githubusercontent.com/54313450/74934455-523d5480-53f7-11ea-9aac-5bc021176269.png)

**Comment by vvmikheev** [comment]
I increased the number of points in experimental design to solve this problem (num_pts in SymmetricLatinHypercube).
It helped somehow...

**Comment by dme65** [comment]
It’s unclear exactly what your settings are, but you need at least `d+1` points to fit an RBF with a linear tail. Thus, if you run in asynchronous mode with `p` workers you need at least `p+d` initial design points.

**Comment by vvmikheev** [comment]
Thank you, I will keep it in mind.
