### ISSUE TITLE
`examples` and `tests` are being installed as top-level packages (directly in site-packages)

### ISSUE THREAD

**Issue by tadeu** [dme65/pySOT#40]
When installing `pySOT` with `pip`, I think that `examples` and `tests` were supposed to be inside the `pySOT` package, but they are installed in a directory outside of it.

**Comment by dme65** [comment]
Thank you for pointing that out! I’ll fix it as soon as I get a chance.

**Comment by dme65** [comment]
Fixed in v0.3.3

**Comment by tadeu** [comment]
Sorry to bother again 😬 
The problem now in v0.3.3 is that there seems to be no `tests` at all in the source release package: https://files.pythonhosted.org/packages/c8/38/9f980e8d985151b59b0d2f38b24ab42407623657e98bbda686d1a9be8ed0/pySOT-0.3.3.tar.gz
and it would be interesting to have those so that they can be run in order to check if a build is ok.

**Comment by dme65** [comment]
You can always git clone the repo to get the tests and examples.  I decided to keep them out since they aren't necessary for the package.  Let me know what you think.

**Comment by tadeu** [comment]
Ok, now that there are releases in GitHub again, I'll start getting the source from the GitHub releases, thanks!
