### ISSUE TITLE
Installing from source doesn't work 

### ISSUE THREAD

**Issue by ilija139** [dme65/pySOT#7]
Following the latest documentation, I try to install it like this:

```
virtualenv .venv
. .venv/bin/activate
git clone https://github.com/dme65/pySOT
cd pySOT
pip install inspyred
python setup.py install
```
I get this error: 
```ImportError: No module named numpy.distutils.core```

Running `python setup.py install` again, for the second time, will complete the installation.

**Comment by dme65** [comment]
The tutorial states that pySOT depends on numpy and my guess is that either you don't have numpy installed or that your installation is outdated. You can either install Anaconda or use
```
pip install numpy --upgrade
```
I hope this takes care of the problem

**Comment by ilija139** [comment]
You are right, I missed that. I thought all the requirements are taken care by the `setup.py` file.
