### ISSUE TITLE
Problem with too many failed function evaluations. 

### ISSUE THREAD

**Issue by ilija139** [dme65/pySOT#9]
The toolbox evaluates the same function evaluations over and over again, when they failed to execute, thus getting stuck in a infinite loop. See #6 and #8.

**Comment by dme65** [comment]
It should be possible to specify a maximal number of failures after which the input is abandoned.

**Comment by dbindel** [comment]
This is a POAP thing, so I have transferred it over there, along with a note that we should update pySOT when I finish the feature.  Closing the issue here for now.
